#pragma once

#define NUMBER_OF_LAYERS 12
#define LAYER_GUI_TOP 11
#define LAYER_GUI_MID 10
#define LAYER_GUI_BOT 9
#define LAYER_GAME_TOP 8
#define LAYER_GAME_CHAR 7
#define LAYER_GAME_DOCKED_CHILD 6
#define LAYER_GAME_DOCKED 5
#define LAYER_GAME_SHIP_CHILD 4
#define LAYER_GAME_SHIP 3
#define LAYER_GAME_STATION_CHILD 2
#define LAYER_GAME_STATION 1
#define LAYER_GAME_BACKGROUND 0